# docker-compose -f compose-api.yml up

version: '3.2'
networks:
  ghosts-network:
    driver: bridge
services:
  postgres:
    image: postgres
    container_name:  ghosts-postgres
    environment:
      POSTGRES_DB: ghosts
      POSTGRES_USER: ghosts
      POSTGRES_PASSWORD: scotty@1
    volumes:
      - ./_data/postgres:/var/lib/postgresql/data
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ghosts"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - ghosts-network
    restart: always
      
  ghosts-api:
    image: ghosts/api
    container_name: ghosts-api
    depends_on:
      - "postgres"
    ports: 
      - "52000:5000"
    networks:
      - ghosts-network

  grafana:
    image: grafana/grafana
    container_name: ghosts-grafana
    depends_on:
      - "postgres"
    ports: 
      - "3000:3000"
    networks:
      - ghosts-network
    volumes:
      - ./_data/grafana:/var/lib/grafana